### ISSUE TITLE
editor insists on "fixing" links

### ISSUE THREAD

**Issue by gnarz** [pittishgunner/tinycms#3]
when creating a link in the editor, it insists on making it an absolute link, including hostname and all. This is bad for 2 reasons:
#1: I create my pages in my local machine and upload them when I'm done. I have to manually fix all links in the source view to make this work...
#2: sometimes it is just plain wrong, like when an relative link to README.html is converted into http://readme.html.

I can't read the javascript code at all, otherwise I would have fixed this.

**Comment by pittishgunner** [comment]
Hey gnarz and thanks for your feedback, as stated here http://www.tinycms.eu/credits/ TinyCMS is using elRTE as an editor thus it's not really a TinyCMS problem. elRTE, just like any major wysiwyg editor, has a html source button which you can easily use to fix problems like that.
