### ISSUE TITLE
_ is converted to - in URLs in the page editor, but not in tcClas5.php:cleanurl()

### ISSUE THREAD

**Issue by gnarz** [pittishgunner/tinycms#4]
subject sais it all. Basically I consider it an error to "fix" any URLs.

**Comment by pittishgunner** [comment]
I'm sorry but I really don't understand what you are saying here, cleanurl() is swapping illegal url characters for "-" and "_" is a legal character which is allowed in urls so it shouldn't be converted.
Maybe you can give a few more details about your problem.

**Comment by pittishgunner** [comment]
You can consider editing yhe a55ets/static/admin,js file on line 2
from:
var opts = {cssClass : 'el-rte',height :450,lang:lang,toolbar  : 'maxi',cssfiles : [SR+'a55ets/static/e1rte/css/elrte-inner.css',(ELI?ELI:'')]}
to:
var opts = {absoluteURLs: false,cssClass : 'el-rte',height :450,lang:lang,toolbar  : 'maxi',cssfiles : [SR+'a55ets/static/e1rte/css/elrte-inner.css',(ELI?ELI:'')]}

On your local installation, that should help you out with your troubles.

**Comment by gnarz** [comment]
Hi,

thanks for the reply, I'll try that tomorrow. If it helps, it might be a good idea to somehow make that available through a55ets/s3ttings.php.

As for the specific problem mentioned in the subject of this mail, this happens in the "Url" input field in the page editor. _ is actually converted to - there (as are uppercase chars to lowercase, which I find weird...).

Oh, and thanks for tinycms, together with mercurial this might be a really neat solution for my website.

Regards,
Gunnar

Es ist keine Schande, vor Angst zu verblöden.

**Comment by gnarz** [comment]
The tip with editing the admin.js worked, thanks.

I can reproduce the _ to - issue at any time like this:

In the admin mode, create a new page. Enter "asd" as title, and "a_d" in the url field. Click on "Create Page" -> contents of url field is converted to "a-d". This also works when I now edit the contents of the url field back to "a_d", and click on "Save Page", again the contents of the url field is converted to "a-d",
